# Generated by Django 5.2.17 on 2026-09-22 23:07

import combinator.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('processing', 'Procesando'), ('done', 'Terminado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploads_purged_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hook', 'Hook'), ('body', 'Body'), ('closer', 'Closer')], max_length=10)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, max_length=500, upload_to=combinator.models.clip_upload_to)),
                ('normalized_file', models.FileField(blank=True, max_length=500, upload_to=combinator.models.clip_normalized_to)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('normalizing', 'Normalizando'), ('ready', 'Listo'), ('failed', 'Error')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='combinator.project')),
            ],
            options={
                'ordering': ['type', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(blank=True, max_length=500, upload_to=combinator.models.variant_output_to)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Listo'), ('failed', 'Error'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='combinator.clip')),
                ('closer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='combinator.clip')),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='combinator.clip')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='combinator.project')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('project', 'hook', 'body', 'closer'), name='unique_variant_combo')],
            },
        ),
    ]
