# Generated by Django 5.2.17 on 2026-09-22 23:37

from itertools import groupby

from django.db import migrations, models


def renumber_clips(apps, schema_editor):
    """Parallel uploads could give several clips the same number; renumber in upload order."""
    Clip = apps.get_model("combinator", "Clip")
    clips = Clip.objects.order_by("project_id", "type", "order", "pk")
    for _, group in groupby(clips, key=lambda c: (c.project_id, c.type)):
        for number, clip in enumerate(group, start=1):
            if clip.order != number:
                clip.order = number
                clip.save(update_fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ('combinator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(renumber_clips, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('project', 'type', 'order'), name='unique_clip_order'),
        ),
    ]
