# Generated by Django 5.2.17 on 2026-09-22 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinator', '0003_public_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='combinator.clip'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='closer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='combinator.clip'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='combinator.clip'),
        ),
    ]
