# Generated by Django 5.2.17 on 2026-09-22 23:58

from itertools import groupby

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Projects generated before modes existed used every combination; number their videos."""
    Project = apps.get_model("combinator", "Project")
    Variant = apps.get_model("combinator", "Variant")
    Project.objects.exclude(status="draft").update(mode="all")
    variants = Variant.objects.order_by("project_id", "pk")
    for _, group in groupby(variants, key=lambda v: v.project_id):
        for position, variant in enumerate(group, start=1):
            variant.position = position
            variant.save(update_fields=["position"])


class Migration(migrations.Migration):

    dependencies = [
        ('combinator', '0004_cascade_variant_clips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['position', 'pk']},
        ),
        migrations.AddField(
            model_name='project',
            name='mode',
            field=models.CharField(choices=[('distinct', 'Variantes distintas'), ('all', 'Todas las combinaciones')], default='distinct', max_length=10),
        ),
        migrations.AddField(
            model_name='variant',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
