# Generated by Django 5.2.17 on 2026-09-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinator', '0005_variation_mode_and_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
