# Generated by Django 5.2.17 on 2026-09-23 00:38

from django.conf import settings
from django.db import migrations, models

from combinator import variation


def backfill(apps, schema_editor):
    """Plan days for projects generated before the plan existed; positions stay as they are."""
    Project = apps.get_model("combinator", "Project")
    for project in Project.objects.exclude(status="draft"):
        variants = list(project.variants.select_related("hook", "body", "closer").order_by("position", "pk"))
        if not variants:
            continue
        footage = lambda clip: clip.sha256 or f"pk:{clip.pk}"  # noqa: E731
        combos = [(v.hook, v.body, v.closer) for v in variants]
        for day, indexes in enumerate(variation.publishing_plan(combos, settings.PUBLISH_MAX_PER_DAY, key=footage), 1):
            for i in indexes:
                variants[i].publish_day = day
                variants[i].save(update_fields=["publish_day"])


class Migration(migrations.Migration):

    dependencies = [
        ('combinator', '0006_clip_sha256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['publish_day', 'position', 'pk']},
        ),
        migrations.AddField(
            model_name='variant',
            name='publish_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
